export const HANDLE_TASK_COMPLETE = "HANDLE_TASK_COMPLETE";
export const ADD_TASK = "ADD_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const SEARCH_TASKS = "SEARCH_TASKS";
export const FILTER_TASKS_BY_COMPLETION = "FILTER_TASKS_BY_COMPLETION";
export const REMOVE_COMPLETED_TASK = "REMOVE_COMPLETED_TASK";
